// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
// / await Firebase.initializeApp(
// /   options: DefaultFirebaseOptions.currentPlatform,
// / );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZyrJ8p0CY_wxnzlClRPqTGlowAj4tROg',
    appId: '1:463567648917:android:1fe8c99b891102330ac39c',
    messagingSenderId: '463567648917',
    projectId: 'addmitto-app',
    databaseURL: 'https://addmitto-app-default-rtdb.firebaseio.com',
    storageBucket: 'addmitto-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWmykt03tx3_AWNTz4H5juQ91jq2zCtvs',
    appId: '1:463567648917:ios:73a58b21f447763b0ac39c',
    messagingSenderId: '463567648917',
    projectId: 'addmitto-app',
    databaseURL: 'https://addmitto-app-default-rtdb.firebaseio.com',
    storageBucket: 'addmitto-app.firebasestorage.app',
    iosClientId: '463567648917-gk23em4jgg77siql74s36tvgmk0eot0p.apps.googleusercontent.com',
    iosBundleId: 'com.addmitto.app',
  );

}